from ursina import rgb

CONST_DEFAULT_GRAVITY = 0.2
CONST_GRAVITY_RANDOMNESS = 0.35
# RENDER_DISTANCE = 7
# HALFRENDER = RENDER_DISTANCE/2 - 1
# SNOW_CEILING = 2.5 * TILE_SCALE
FOG_ENABLED = False

#TERRAIN GENERATION STUFF
TILE_SCALE = 50
TERRAIN_Y_MULT = 1.7
SPAWN_MULT = 2

FB = FOG_BASE = 170

INVENTORY_HEIGHT = 5
INVENTORY_WIDTH = 9

from .entities import * #Entities needs to import the inventory width and height


BIOMESCALE = 40
SECONDARY_BIOMESCALE = 40
AFFINITY_BIOMESCALE =250

CHEST_SCALE = 1

EMPTY = 0.1
EMPTY_SPAWN_MULTIPLIER = 0.2
EMPTY_PREFIX = "Empty "
SPARSE = 0.2
SPARSE_SPAWN_MULTIPLIER = 0.5
SPARSE_PREFIX = "Sparse "
ACCUSTOMED = 0.4
ACCUSTOMED_SPAWN_MULTIPLIER = 0.7
ACCUSTOMED_PREFIX = "Accustomed"
PROFUSE = 0.7
PROFUSE_SPAWN_MULTIPLIER = 0.9
PROFUSE_PREFIX = "Profuse"
RICH = 0.9
RICH_SPAWN_MULTIPLIER = 1.2
RICH_PREFIX = "Rich"
ABUNDANT = 1.0
ABUNDANT_SPAWN_MULTIPLIER = 1.4
ABUNDANT_PREFIX = "Abundant"

MODIFIER_MAP = {
	EMPTY		:(EMPTY_SPAWN_MULTIPLIER, 		EMPTY_PREFIX),
	SPARSE		:(SPARSE_SPAWN_MULTIPLIER, 		SPARSE_PREFIX),
	ACCUSTOMED	:(ACCUSTOMED_SPAWN_MULTIPLIER, 	ACCUSTOMED_PREFIX),
	PROFUSE		:(PROFUSE_SPAWN_MULTIPLIER, 	PROFUSE_PREFIX),
	RICH		:(RICH_SPAWN_MULTIPLIER, 		RICH_PREFIX),
	ABUNDANT	:(ABUNDANT_SPAWN_MULTIPLIER, 	ABUNDANT_PREFIX),
}

EVIL = -0.33
EVIL_PREFIX ="Evil "
EVIL_COLOR_EFFECT = (-20,-20,-20)

CRUEL = -0.13
CRUEL_PREFIX ="Cruel "
CRUEL_COLOR_EFFECT = (-10,-10,-10)

BENEIGN = 0.13
BENEIGN_PREFIX = " "
BENEIGN_COLOR_EFFECT = (0,0,0)

ATTUNED = 0.33
ATTUNED_PREFIX = "Attuned "
ATTUNED_COLOR_EFFECT = (10,10,10)

MAGIC = 1
MAGIC_PREFIX = "Magical "
MAGIC_COLOR_EFFECT = (20,20,20)

AFFINITY_MAP = {
	EVIL:		(EVIL_COLOR_EFFECT,EVIL_PREFIX),
	CRUEL: 		(CRUEL_COLOR_EFFECT,CRUEL_PREFIX),
	BENEIGN:	(BENEIGN_COLOR_EFFECT,BENEIGN_PREFIX),
	ATTUNED: 	(ATTUNED_COLOR_EFFECT,ATTUNED_PREFIX),
	MAGIC:		(MAGIC_COLOR_EFFECT,MAGIC_PREFIX),
}



#17

DESERT_COLOR = rgb(248,165,85)
DESERT_FLOOR_COLOR = rgb(245,119,34)

SCORCHED_COLOR = rgb(253,180,86)
SCORCHED_FLOOR_COLOR = rgb(248,144,31)

PARCHED_COLOR = rgb(253,200,84)
PARCHED_FLOOR_COLOR = rgb(251,171,24)

BARREN_COLOR = rgb(252,220,83)
BARREN_FLOOR_COLOR = rgb(255,200,9)

FIELDS_COLOR = rgb(251,238,82)
FIELDS_FLOOR_COLOR = rgb(230,204,29)

SCRUBLAND_COLOR = rgb(221,223,125)
SCRUBLAND_FLOOR_COLOR = rgb(192,215,47)

LIGHT_FOREST_COLOR = rgb(174,209,79)
LIGHT_FOREST_FLOOR_COLOR = rgb(137,197,63)

HEAVY_FOREST_COLOR = rgb(130,197,82)
HEAVY_FOREST_FLOOR_COLOR = rgb(74,184,72)

JUNGLE_COLOR = rgb(90,187,71)
JUNGLE_FLOOR_COLOR = rgb(33,175,75)

SWAMP_COLOR = rgb(240,86,58)
SWAMP_FLOOR_COLOR = rgb(236,29,35)

BOG_COLOR = rgb(205,78,157)
BOG_FLOOR_COLOR = rgb(196,26,125)

MARSH_COLOR = rgb(130,78,160)
MARSH_FLOOR_COLOR = rgb(96,46,145)

QUAGMIRE_COLOR = rgb(167,149,201)
QUAGMIRE_FLOOR_COLOR = rgb(33,67,156)

TEMPERATE_COLOR = rgb(150,156,206)
TEMPERATE_FLOOR_COLOR = rgb(75,88,167)

TUNDRA_COLOR = rgb(150,156,206)
TUNDRA_FLOOR_COLOR = rgb(75,88,167)

PERMAFROST_COLOR = rgb(69,140,204)
PERMAFROST_FLOOR_COLOR = rgb(24,95,173)

ICE_COLOR = rgb(66,190,216)
ICE_FLOOR_COLOR = rgb(16,160,197)





#Primary Biomes
DESERT = 1
DESERT_CHANCE = -0.35
DESERT_MAP_COLOR = DESERT_FLOOR_COLOR
DESERT_FOG_DENSITY = 0
DESERT_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
DESERT_SNOW = 0.0
DESERT_SKYBOX_COLOR = DESERT_FOG_COLOR
DESERT_RENDER_RANGE = 9
DESERT_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}

SCORCHED = 2
SCORCHED_CHANCE = -0.25
SCORCHED_MAP_COLOR = SCORCHED_FLOOR_COLOR
SCORCHED_FOG_DENSITY = 0
SCORCHED_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
SCORCHED_SNOW = 0.0
SCORCHED_SKYBOX_COLOR = SCORCHED_FOG_COLOR
SCORCHED_RENDER_RANGE = 9
SCORCHED_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


PARCHED = 3
PARCHED_CHANCE = -0.15
PARCHED_MAP_COLOR = PARCHED_FLOOR_COLOR
PARCHED_FOG_DENSITY = 0
PARCHED_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
PARCHED_SNOW = 0.0
PARCHED_SKYBOX_COLOR = PARCHED_FOG_COLOR
PARCHED_RENDER_RANGE = 9
PARCHED_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


BARREN = 4
BARREN_CHANCE = -0.035
BARREN_MAP_COLOR = BARREN_FLOOR_COLOR
BARREN_FOG_DENSITY = 0
BARREN_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
BARREN_SNOW = 0.0
BARREN_SKYBOX_COLOR = BARREN_FOG_COLOR
BARREN_RENDER_RANGE = 9
BARREN_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


FIELDS = 5
FIELDS_CHANCE = 0.035
FIELDS_MAP_COLOR = FIELDS_FLOOR_COLOR
FIELDS_FOG_DENSITY = 0
FIELDS_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
FIELDS_SNOW = 0.0
FIELDS_SKYBOX_COLOR = FIELDS_FOG_COLOR
FIELDS_RENDER_RANGE = 9
FIELDS_MAP = {
	0.02  : Crystal,
	0.028 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


SCRUBLAND = 6
SCRUBLAND_CHANCE = 0.15
SCRUBLAND_MAP_COLOR = SCRUBLAND_FLOOR_COLOR
SCRUBLAND_FOG_DENSITY = 0
SCRUBLAND_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
SCRUBLAND_SNOW = 0.0
SCRUBLAND_SKYBOX_COLOR = SCRUBLAND_FOG_COLOR
SCRUBLAND_RENDER_RANGE = 9
SCRUBLAND_MAP = {
	0.02  : Crystal,
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


LIGHT_FOREST = 7
LIGHT_FOREST_CHANCE = 0.25
LIGHT_FOREST_MAP_COLOR = LIGHT_FOREST_FLOOR_COLOR
LIGHT_FOG_DENSITY = (0,130)
LIGHT_FOG_COLOR = rgb(FB-20,FB-20,FB-20)
LIGHT_SNOW = 0.3
LIGHT_SKYBOX_COLOR = LIGHT_FOG_COLOR
LIGHT_RENDER_RANGE = 9
LIGHT_FOREST_MAP = {
	0.004 : StickBall,
	0.014 : Rock,
	0.024 : SharpRock,
	0.036 : Log,
	0.046 : SmallMushroom,
	0.057 : Stump,
	0.072 : Branch,
	0.154 : Tree,
}

HEAVY_FOREST = 8
HEAVY_FOREST_CHANCE = 0.35
HEAVY_FOREST_MAP_COLOR = HEAVY_FOREST_FLOOR_COLOR
HEAVY_FOG_DENSITY = (0,90)
HEAVY_FOG_COLOR = rgb(FB-30,FB-30,FB-30)
HEAVY_SNOW = 0.3
HEAVY_SKYBOX_COLOR = HEAVY_FOG_COLOR
HEAVY_RENDER_RANGE = 9
HEAVY_FOREST_MAP = {
	0.006 : StickBall,
	0.014 : Rock,
	0.030 : SharpRock,
	0.045 : Log,
	0.054 : SmallMushroom,
	0.062 : Mushroom,
	0.068 : Stump,
	0.080 : Branch,
	0.176 : Tree,
}

JUNGLE = 9
JUNGLE_CHANCE = 1.0
JUNGLE_MAP_COLOR = JUNGLE_FLOOR_COLOR
JUNGLE_FOG_DENSITY = 0
JUNGLE_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
JUNGLE_SNOW = 0.0
JUNGLE_SKYBOX_COLOR = JUNGLE_FOG_COLOR
JUNGLE_RENDER_RANGE = 9
JUNGLE_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}






#Secondary Biomes
SWAMP = 10
SWAMP_CHANCE = -0.35
SWAMP_MAP_COLOR = SWAMP_FLOOR_COLOR
SWAMP_FOG_DENSITY = 0
SWAMP_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
SWAMP_SNOW = 0.0
SWAMP_SKYBOX_COLOR = SWAMP_FOG_COLOR
SWAMP_RENDER_RANGE = 9
SWAMP_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}

BOG = 11
BOG_CHANCE = -0.25
BOG_MAP_COLOR = BOG_FLOOR_COLOR
BOG_FOG_DENSITY = 0
BOG_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
BOG_SNOW = 0.0
BOG_SKYBOX_COLOR = BOG_FOG_COLOR
BOG_RENDER_RANGE = 9
BOG_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


MARSH = 12
MARSH_CHANCE = -0.15
MARSH_MAP_COLOR = MARSH_FLOOR_COLOR
MARSH_FOG_DENSITY = 0
MARSH_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
MARSH_SNOW = 0.0
MARSH_SKYBOX_COLOR = MARSH_FOG_COLOR
MARSH_RENDER_RANGE = 9
MARSH_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


QUAGMIRE = 13
QUAGMIRE_CHANCE = -0.035
QUAGMIRE_MAP_COLOR = QUAGMIRE_FLOOR_COLOR
QUAGMIRE_FOG_DENSITY = 0
QUAGMIRE_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
QUAGMIRE_SNOW = 0.0
QUAGMIRE_SKYBOX_COLOR = QUAGMIRE_FOG_COLOR
QUAGMIRE_RENDER_RANGE = 9
QUAGMIRE_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}

TEMPERATE = 14
TEMPERATE_CHANCE = .15
TEMPERATE_MAP_COLOR = TEMPERATE_FLOOR_COLOR
TEMPERATE_FOG_DENSITY = 0
TEMPERATE_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
TEMPERATE_SNOW = 0.0
TEMPERATE_SKYBOX_COLOR = TEMPERATE_FOG_COLOR
TEMPERATE_RENDER_RANGE = 9
TEMPERATE_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


TUNDRA = 15
TUNDRA_CHANCE = .25
TUNDRA_MAP_COLOR = TUNDRA_FLOOR_COLOR
TUNDRA_FOG_DENSITY = (0,130)
TUNDRA_FOG_COLOR = rgb(FB-20,FB-20,FB-20)
TUNDRA_SNOW = 0.3
TUNDRA_SKYBOX_COLOR = TUNDRA_FOG_COLOR
TUNDRA_RENDER_RANGE = 9
TUNDRA_MAP = {
	0.004 : StickBall,
	0.014 : Rock,
	0.024 : SharpRock,
	0.036 : Log,
	0.046 : SmallMushroom,
	0.057 : Stump,
	0.072 : Branch,
	0.154 : Tree,
}

PERMAFROST = 16
PERMAFROST_CHANCE = .35
PERMAFROST_MAP_COLOR = PERMAFROST_FLOOR_COLOR
PERMAFROST_FOG_DENSITY = (0,90)
PERMAFROST_FOG_COLOR = rgb(FB-30,FB-30,FB-30)
PERMAFROST_SNOW = 0.3
PERMAFROST_SKYBOX_COLOR = PERMAFROST_FOG_COLOR
PERMAFROST_RENDER_RANGE = 9
PERMAFROST_MAP = {
	0.006 : StickBall,
	0.014 : Rock,
	0.030 : SharpRock,
	0.045 : Log,
	0.054 : SmallMushroom,
	0.062 : Mushroom,
	0.068 : Stump,
	0.080 : Branch,
	0.176 : Tree,
}

ICE = 17
ICE_CHANCE = 1
ICE_MAP_COLOR = ICE_FLOOR_COLOR
ICE_FOG_DENSITY = 0
ICE_FOG_COLOR = rgb(FB-60,FB-60,FB-70)
ICE_SNOW = 0.0
ICE_SKYBOX_COLOR = ICE_FOG_COLOR
ICE_RENDER_RANGE = 9
ICE_MAP = {
	0.018 : Rock,
	0.064 : Mushroom,
	0.074 : MushroomCircle,
	0.170 : Tree,
}


BIOME_SPAWN_MAP = {
	DESERT : DESERT_CHANCE,
	SCORCHED : SCORCHED_CHANCE,
	PARCHED : PARCHED_CHANCE,
	BARREN : BARREN_CHANCE,
	FIELDS : FIELDS_CHANCE,
	SCRUBLAND : SCRUBLAND_CHANCE,
	LIGHT_FOREST : LIGHT_FOREST_CHANCE,
	HEAVY_FOREST : HEAVY_FOREST_CHANCE,
	JUNGLE : JUNGLE_CHANCE,
	SWAMP : SWAMP_CHANCE,
	BOG : BOG_CHANCE,
	MARSH : MARSH_CHANCE,
	QUAGMIRE : QUAGMIRE_CHANCE,
	FIELDS : FIELDS_CHANCE,
	TEMPERATE : TEMPERATE_CHANCE,
	TUNDRA : TUNDRA_CHANCE,
	PERMAFROST : PERMAFROST_CHANCE,
	ICE : ICE_CHANCE,
}

BIOME_NAME_MAP = {
	DESERT : "Desert",
	SCORCHED : "Scorched",
	PARCHED : "Parched",
	BARREN : "Barren", 
	FIELDS : "Fields",
	SCRUBLAND : "Scrubland",
	LIGHT_FOREST :"Light Forest", 
	HEAVY_FOREST : "Heavy Forest",
	JUNGLE : "Jungle",
	SWAMP : "Swamp",
	BOG : "Bog",
	MARSH : "Marsh",
	QUAGMIRE : "Quagmire", 
	FIELDS : "Fields",
	TEMPERATE : "Temperate",
	TUNDRA :"Tundra", 
	PERMAFROST : "Permafrost",
	ICE : "Ice",
}

MAP_COLOR = {
	DESERT : DESERT_MAP_COLOR,
	SCORCHED : SCORCHED_MAP_COLOR,
	PARCHED : PARCHED_MAP_COLOR,
	BARREN : BARREN_MAP_COLOR,
	FIELDS : FIELDS_MAP_COLOR,
	SCRUBLAND : SCRUBLAND_MAP_COLOR,
	HEAVY_FOREST : HEAVY_FOREST_MAP_COLOR,
	LIGHT_FOREST : LIGHT_FOREST_MAP_COLOR,
	JUNGLE :	JUNGLE_MAP_COLOR,
	SWAMP : SWAMP_MAP_COLOR,
	BOG : BOG_MAP_COLOR,
	MARSH : MARSH_MAP_COLOR,
	QUAGMIRE : QUAGMIRE_MAP_COLOR,
	FIELDS : FIELDS_MAP_COLOR,
	TEMPERATE : TEMPERATE_MAP_COLOR,
	TUNDRA : TUNDRA_MAP_COLOR,
	PERMAFROST : PERMAFROST_MAP_COLOR,
	ICE :	ICE_MAP_COLOR,
}

TERRAIN_COLOR = {
	DESERT : DESERT_FLOOR_COLOR,
	SCORCHED : SCORCHED_FLOOR_COLOR,
	PARCHED : PARCHED_FLOOR_COLOR,
	BARREN : BARREN_FLOOR_COLOR,
	FIELDS : FIELDS_FLOOR_COLOR,
	SCRUBLAND : SCRUBLAND_FLOOR_COLOR,
	HEAVY_FOREST : HEAVY_FOREST_FLOOR_COLOR,
	LIGHT_FOREST : LIGHT_FOREST_FLOOR_COLOR,
	JUNGLE :	JUNGLE_FLOOR_COLOR,
	SWAMP : SWAMP_FLOOR_COLOR,
	BOG : BOG_FLOOR_COLOR,
	MARSH : MARSH_FLOOR_COLOR,
	QUAGMIRE : QUAGMIRE_FLOOR_COLOR,
	FIELDS : FIELDS_FLOOR_COLOR,
	TEMPERATE : TEMPERATE_FLOOR_COLOR,
	TUNDRA : TUNDRA_FLOOR_COLOR,
	PERMAFROST : PERMAFROST_FLOOR_COLOR,
	ICE :	ICE_FLOOR_COLOR,
}

BIOME_MAP = {
	DESERT : (DESERT_COLOR, DESERT_MAP),
	SCORCHED : (SCORCHED_COLOR, SCORCHED_MAP),
	PARCHED : (PARCHED_COLOR, PARCHED_MAP),
	BARREN : (BARREN_COLOR, BARREN_MAP),
	FIELDS : (FIELDS_COLOR, FIELDS_MAP),
	SCRUBLAND : (SCRUBLAND_COLOR, SCRUBLAND_MAP),
	LIGHT_FOREST : (LIGHT_FOREST_COLOR, LIGHT_FOREST_MAP),
	HEAVY_FOREST : (HEAVY_FOREST_COLOR, HEAVY_FOREST_MAP),
	JUNGLE : (JUNGLE_COLOR, JUNGLE_MAP),
	SWAMP : (SWAMP_COLOR, SWAMP_MAP),
	BOG : (BOG_COLOR, BOG_MAP),
	MARSH : (MARSH_COLOR, MARSH_MAP),
	QUAGMIRE : (QUAGMIRE_COLOR, QUAGMIRE_MAP),
	FIELDS : (FIELDS_COLOR, FIELDS_MAP),
	TEMPERATE : (TEMPERATE_COLOR, TEMPERATE_MAP),
	TUNDRA : (TUNDRA_COLOR, TUNDRA_MAP),
	PERMAFROST : (PERMAFROST_COLOR, PERMAFROST_MAP),
	ICE : (ICE_COLOR, ICE_MAP),
}

BIOME_SPAWN_MAP = {
	DESERT_CHANCE : DESERT,
	SCORCHED_CHANCE : SCORCHED,
	PARCHED_CHANCE : PARCHED,
	BARREN_CHANCE : BARREN,
	FIELDS_CHANCE : FIELDS,
	SCRUBLAND_CHANCE : SCRUBLAND,
	LIGHT_FOREST_CHANCE : LIGHT_FOREST,
	HEAVY_FOREST_CHANCE : HEAVY_FOREST,
	JUNGLE_CHANCE : JUNGLE,
}

SECONDARY_BIOME_SPAWN_MAP = {
	SWAMP_CHANCE : SWAMP,
	BOG_CHANCE : BOG,
	MARSH_CHANCE : MARSH,
	QUAGMIRE_CHANCE : QUAGMIRE,
	FIELDS_CHANCE : FIELDS,
	TEMPERATE_CHANCE : TEMPERATE,
	TUNDRA_CHANCE : TUNDRA,
	PERMAFROST_CHANCE : PERMAFROST,
	ICE_CHANCE : ICE,
}

EFFECT_LEVELS = {
	DESERT : (DESERT_FOG_DENSITY, DESERT_FOG_COLOR, DESERT_SNOW, DESERT_RENDER_RANGE, DESERT_SKYBOX_COLOR),
	SCORCHED : (SCORCHED_FOG_DENSITY, SCORCHED_FOG_COLOR, SCORCHED_SNOW, SCORCHED_RENDER_RANGE, SCORCHED_SKYBOX_COLOR),
	PARCHED : (PARCHED_FOG_DENSITY, PARCHED_FOG_COLOR, PARCHED_SNOW, PARCHED_RENDER_RANGE, PARCHED_SKYBOX_COLOR),
	BARREN : (BARREN_FOG_DENSITY, BARREN_FOG_COLOR, BARREN_SNOW, BARREN_RENDER_RANGE, BARREN_SKYBOX_COLOR),
	FIELDS :(FIELDS_FOG_DENSITY, FIELDS_FOG_COLOR, FIELDS_SNOW, FIELDS_RENDER_RANGE, FIELDS_SKYBOX_COLOR),
	SCRUBLAND : (SCRUBLAND_FOG_DENSITY, SCRUBLAND_FOG_COLOR, SCRUBLAND_SNOW, SCRUBLAND_RENDER_RANGE, SCRUBLAND_SKYBOX_COLOR),
	LIGHT_FOREST : (LIGHT_FOG_DENSITY, LIGHT_FOG_COLOR, LIGHT_SNOW, LIGHT_RENDER_RANGE, LIGHT_SKYBOX_COLOR),
	HEAVY_FOREST : (HEAVY_FOG_DENSITY, HEAVY_FOG_COLOR, HEAVY_SNOW, HEAVY_RENDER_RANGE, HEAVY_SKYBOX_COLOR),
	JUNGLE : (JUNGLE_FOG_DENSITY, JUNGLE_FOG_COLOR, JUNGLE_SNOW, JUNGLE_RENDER_RANGE, JUNGLE_SKYBOX_COLOR),
	SWAMP : (SWAMP_FOG_DENSITY, SWAMP_FOG_COLOR, SWAMP_SNOW, SWAMP_RENDER_RANGE, SWAMP_SKYBOX_COLOR),
	BOG : (BOG_FOG_DENSITY, BOG_FOG_COLOR, BOG_SNOW, BOG_RENDER_RANGE, BOG_SKYBOX_COLOR),
	MARSH : (MARSH_FOG_DENSITY, MARSH_FOG_COLOR, MARSH_SNOW, MARSH_RENDER_RANGE, MARSH_SKYBOX_COLOR),
	QUAGMIRE : (QUAGMIRE_FOG_DENSITY, QUAGMIRE_FOG_COLOR, QUAGMIRE_SNOW, QUAGMIRE_RENDER_RANGE, QUAGMIRE_SKYBOX_COLOR),
	FIELDS :(FIELDS_FOG_DENSITY, FIELDS_FOG_COLOR, FIELDS_SNOW, FIELDS_RENDER_RANGE, FIELDS_SKYBOX_COLOR),
	TEMPERATE : (TEMPERATE_FOG_DENSITY, TEMPERATE_FOG_COLOR, TEMPERATE_SNOW, TEMPERATE_RENDER_RANGE, TEMPERATE_SKYBOX_COLOR),
	TUNDRA : (TUNDRA_FOG_DENSITY, TUNDRA_FOG_COLOR, TUNDRA_SNOW, TUNDRA_RENDER_RANGE, TUNDRA_SKYBOX_COLOR),
	PERMAFROST : (PERMAFROST_FOG_DENSITY, PERMAFROST_FOG_COLOR, PERMAFROST_SNOW, PERMAFROST_RENDER_RANGE, PERMAFROST_SKYBOX_COLOR),
	ICE : (ICE_FOG_DENSITY, ICE_FOG_COLOR, ICE_SNOW, ICE_RENDER_RANGE, ICE_SKYBOX_COLOR),
}